export const Khatatiobj = {
  1: {
    id: "1khatati",
    name: "خطاطی 1",
    category: "خطاطی",
    artist: "احمدرضا اقدسی",
    image: "images/khatati1.jpg",
    price: "12,700",
  },
  2: {
    id: "2khatati",
    name: "خطاطی 2",
    category: "خطاطی",
    artist: "مریم زارعی",
    image: "images/khatati2.jpg",
    price: "14,200",
  },
  3: {
    id: "3khatati",
    name: "خطاطی 3",
    category: "خطاطی",
    artist: "احمد صادقلو",
    image: "images/khatati3.jpg",
    price: "6,700",
  },
  4: {
    id: "4khatati",
    name: "خطاطی 4",
    category: "خطاطی",
    artist: "روشنک وحیدیان",
    image: "images/khatati4.jpg",
    price: "3,900",
  },
  5: {
    id: "5khatati",
    name: "خطاطی 5",
    category: "خطاطی",
    artist: "سعید آقاخان",
    image: "images/khatati5.jpg",
    price: "42,200",
  },
  6: {
    id: "6khatati",
    name: "خطاطی 6",
    category: "خطاطی",
    artist: "حسین منصوری",
    image: "images/khatati6.jpg",
    price: "8,450",
  },
  7: {
    id: "7khatati",
    name: "خطاطی 7",
    category: "خطاطی",
    artist: "طاهره حسینی",
    image: "images/khatati7.jpg",
    price: "12,900",
  },
  8: {
    id: "8khatati",
    name: "خطاطی 8",
    category: "خطاطی",
    artist: "رضا منصوری",
    image: "images/khatati8.jpg",
    price: "5,300",
  },
  9: {
    id: "9khatati",
    name: "خطاطی 9",
    category: "خطاطی",
    artist: "احمدرضا صالحی",
    image: "images/khatati9.jpg",
    price: "12,350",
  },
  10: {
    id: "10khatati",
    name: "خطاطی 10",
    category: "خطاطی",
    artist: "فرزاد کلان",
    image: "images/khatati10.jpg",
    price: "5,200",
  },
  11: {
    id: "11khatati",
    name: "خطاطی 11",
    category: "خطاطی",
    artist: "نسرین ثابتی",
    image: "images/khatati11.jpg",
    price: "10,100",
  },
  12: {
    id: "12khatati",
    name: "خطاطی 12",
    category: "خطاطی",
    artist: "نسرین محمودی",
    image: "images/khatati12.jpg",
    price: "21,350",
  },
  13: {
    id: "13khatati",
    name: "خطاطی 13",
    category: "خطاطی",
    artist: "حامد احمد خانی",
    image: "images/khatati13.jpg",
    price: "32,650",
  },
  14: {
    id: "14khatati",
    name: "خطاطی 14",
    category: "خطاطی",
    artist: "نسرین محمودی",
    image: "images/khatati14.jpg",
    price: "24,650",
  },
  15: {
    id: "15khatati",
    name: "خطاطی 15",
    category: "خطاطی",
    artist: "صادق نبویان",
    image: "images/khatati15.jpg",
    price: "8,200",
  },
  16: {
    id: "16khatati",
    name: "خطاطی 16",
    category: "خطاطی",
    artist: "سوسن منتظری",
    image: "images/khatati16.jpg",
    price: "9,450",
  },
}
