export const mainArtsObj = {
  1: {
    id: "1main",
    name: "کار روستا",
    category: "نقاشی",
    color: "رنگ روغن",
    artist: "احمد صادقلو",
    image: "images/sheep.jpg",
    price: "1,500",
  },
  2: {
    id: "2main",
    name: "شب پرستاره",
    category: "نقاشی",
    category: "نقاشی",
    color: "رنگ روغن",
    artist: "ون گوک",
    image: "/images/StarryNight.jpg",
    price: "32,500",
  },
  3: {
    id: "3main",
    name: "کلیسای شلوغ",
    category: "نقاشی",
    color: "رنگ آکریلیک",
    artist: "رامبرانت",
    image: "/images/church.jpg",
    price: "63,300",
  },
  4: {
    id: "4main",
    name: "جنگل",
    category: "نقاشی",
    color: "رنگ آکریلیک",
    artist: "داوینچی",
    image: "/images/tree.jpg",
    price: "25,100",
  },
  5: {
    id: "5main",
    name: "گل ها",
    category: "نقاشی",
    color: "رنگ روغن",
    artist: "علیرضا توسلی",
    image: "/images/flower.jpg",
    price: "13,700",
  },
  6: {
    id: "6main",
    name: "مسیح در طوفان دریای جلیل",
    category: "نقاشی",
    color: "رنگ آکرلیک",
    artist: "رامبرانت",
    image: "/images/moses.jpg",
    price: "24,700",
  },
}
