export const specificObj = {
  1: {
    id: "1nature",
    name: "باران",
    category: "نقاشی",
    specificCategory: "طبیعت",
    artist: "ویلیام مارشال",
    image: "images/nature1.png",
    price: "12,700",
  },
  2: {
    id: "2nature",
    name: "گل های پژمرده",
    category: "نقاشی",
    specificCategory: "طبیعت",
    artist: "ون گوک",
    image: "images/nature2.jpg",
    price: "14,200",
  },
  3: {
    id: "3nature",
    name: "آدم ها",
    category: "تابلوفرش",
    specificCategory: "طبیعت",
    artist: "احمد صادقلو",
    image: "images/nature3.jpg",
    price: "6,700",
  },
  4: {
    id: "4nature",
    name: "تونل عشق",
    category: "عکس",
    specificCategory: "طبیعت",
    artist: "رومن ولیون",
    image: "images/nature4.jpeg",
    price: "3,900",
  },
  5: {
    id: "1ocean",
    name: "جنگ آبها",
    category: "نقاشی",
    specificCategory: "دریا",
    artist: "لودولف باکایزن",
    image: "images/ocean1.jpg",
    price: "42,200",
  },
  6: {
    id: "2ocean",
    name: "زندگی جای دیگری است",
    category: "عکس",
    specificCategory: "دریا",
    artist: "رومن ویلون",
    image: "images/ocean2.jpeg",
    price: "8,450",
  },
  7: {
    id: "3ocean",
    name: "صخره ها",
    category: "طراحی",
    specificCategory: "دریا",
    artist: "بیوک احمدی",
    image: "images/ocean3.jpeg",
    price: "12,900",
  },
  8: {
    id: "4ocean",
    name: "دریای فرانسه",
    category: "تابلوفرش",
    specificCategory: "دریا",
    artist: "رضا منصوری",
    image: "images/ocean4.png",
    price: "5,300",
  },
  9: {
    id: "1animals",
    name: "نگاه",
    category: "طراحی",
    specificCategory: "حیوانات",
    artist: "داریوش حامدی",
    image: "images/animals1.jpeg",
    price: "12,350",
  },
  10: {
    id: "2animals",
    name: "استبل آنتیلوپ",
    category: "عکس",
    specificCategory: "حیوانات",
    artist: "کلاد گویلامین",
    image: "images/animals2.jpeg",
    price: "5,200",
  },
  11: {
    id: "3animals",
    name: "چشم",
    category: "عکس",
    specificCategory: "حیوانات",
    artist: "دنیلا واسیلوا",
    image: "images/animals3.jpeg",
    price: "10,100",
  },
  12: {
    id: "4animals",
    name: "آرامش بوفالو ها",
    category: "نقاشی",
    specificCategory: "حیوانات",
    artist: "نسرین محمودی",
    image: "images/animals4.jpeg",
    price: "21,350",
  },
  13: {
    id: "1village",
    name: "خیابان روستا در اوورز",
    category: "نقاشی",
    specificCategory: "روستا",
    artist: "ون گوک",
    image: "images/village1.jpg",
    price: "32,650",
  },
  14: {
    id: "2village",
    name: "پیاده روی در روستا",
    category: "نقاشی",
    specificCategory: "روستا",
    artist: "پل لدنت",
    image: "images/village2.jpeg",
    price: "24,650",
  },
  15: {
    id: "3village",
    name: "روزی روزگاری در روتردام",
    category: "طراحی",
    specificCategory: "روستا",
    artist: "امیلیا ک",
    image: "images/village3.jpeg",
    price: "8,200",
  },
  16: {
    id: "4village",
    name: "منظره روستایی",
    category: "طراحی",
    specificCategory: "روستا",
    artist: "سوسن منتظری",
    image: "images/village4.jpeg",
    price: "9,450",
  },
  
}
