export const vanGoghObj = {
    1: {
      id: "1van",
      name: "سیب زمینی خواران",
      category: "نقاشی",
      color: "رنگ روغن",
      artist: "ون گوک",
      image: "images/vangogh1.jpg",
      price: "19,350",
    },
    2: {
      id: "2van",
      name: "اُتاقِ خوابِ آرل",
      category: "نقاشی",
      color: "رنگ روغن",
      artist: "ون گوک",
      image: "/images/vangogh2.jpg",
      price: "22,700",
    },
    3: {
      id: "3van",
      name: "گل‌های آفتابگردان",
      category: "نقاشی",
      color: "رنگ روغن",
      artist: "ون گوک",
      image: "/images/vangogh3.jpg",
      price: "37,570",
    },
    4: {
      id: "4van",
      name: "کافه تراس در شب",
      category: "نقاشی",
      color: "رنگ روغن",
      artist: "ون گوک",
      image: "/images/vangogh4.jpg",
      price: "25,100",
    },
    5: {
      id: "5van",
      name: "بذرپاش",
      category: "نقاشی",
      color: "رنگ روغن",
      artist: "ون گوک",
      image: "/images/vangogh5.jpg",
      price: "17,700",
    },
    6: {
      id: "6van",
      name: "گندم‌زاری با سروها ",
      category: "نقاشی",
      color: "رنگ روغن",
      artist: "ون گوک",
      image: "/images/vangogh6.jpg",
      price: "26,240",
    },
    7: {
      id: "7van",
      name: "شکوفه های بادام",
      category: "نقاشی",
      color: "رنگ روغن",
      artist: "ون گوک",
      image: "/images/vangogh7.jpg",
      price: "29,300",
    },
    8: {
      id: "8van",
      name: "کلیسای اوورز",
      category: "نقاشی",
      color: "رنگ روغن",
      artist: "ون گوک",
      image: "/images/vangogh8.jpg",
      price: "37,150",
    },
    
  }
  